import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "introduction",
          label: "✨ Introduction",
        },
        {
          type: "doc",
          id: "sync",
          label: "🔄 Sync",
        },
        {
          type: "doc",
          id: "ways-of-organization",
          label: "🗂️ Ways of Organization",
        },
        {
          type: "doc",
          id: "rich-text-editor",
          label: "✍️ Rich-Text Editor",
        },
        {
          type: "doc",
          id: "mobile-app",
          label: "📱 Mobile App",
        },
      ],
    },

    {
      type: "category",
      label: "Concepts",
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "attributes",
          label: "🏷️ Attributes",
        },
        {
          type: "doc",
          id: "collections",
          label: "📊 Collections",
        },
        {
          type: "doc",
          id: "filters",
          label: "🔎 Filters",
        },
        {
          type: "doc",
          id: "task-management",
          label: "✅ Task Management",
        },
        {
          type: "doc",
          id: "templates",
          label: "📄 Templates",
        },
        {
          type: "doc",
          id: "quick-add",
          label: "➕ Quick Add",
        },
      ],
    },
    {
      type: "category",
      label: "In Detail",
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "app-settings",
          label: "⚙️ App Settings",
        },
        {
          type: "doc",
          id: "cmd-k",
          label: "⚡ Command Menu",
        },
        {
          type: "doc",
          id: "flashcards",
          label: "📚 Flashcards",
        },
      ],
    },
  ],
};

export default sidebars;
